data:

  index:
    train: "data/index/train.csv"
    val: "data/index/val.csv"
    test: "data/index/test.csv"

  image_size: [576, 832]
  

model_info:
  encoder_name: "mobilenet_v2"
  encoder_weights: "imagenet"
  classes: 59  # Number of classes
  in_channels: 3  # Input image channels

training:
  learning_rate: 0.003

  trainer_kwargs:
    max_epochs: 100
    accelerator: "gpu"
    devices: 1
    fast_dev_run: false  # Set to true to run quick test
    limit_train_batches: 0.02

  dataloader_kwargs:
    shuffle: true
    batch_size: 8
    pin_memory: false
    num_workers: 10

eval:
  checkpoint_path: null

  dataloader_kwargs:
    shuffle: false
    batch_size: 8
    pin_memory: false
    num_workers: 10